package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Tuesday, June 17, 2014 4:32:56 PM WIB
*/

public interface HelloOperations 
{
  String sayHello ();

  // This line is an operation statement.
  void shutdown ();
} // interface HelloOperations
